CREATE TABLE MEMBERS(MEMBER_ID INTEGER NOT NULL, MEMBER_NAME VARCHAR2(255), PASSWORD VARCHAR2(255), CREATE_DATE TIMESTAMP , UPDATE_DATE TIMESTAMP, DELETE_YN CHAR NOT NULL, PRIMARY KEY (MEMBER_ID))
/*INSERT INTO MEMBERS(MEMBER_ID, MEMBER_NAME)VALUES(2,'TEST1')*/
CREATE SEQUENCE MEMBER_ID_SEQ START WITH 1 INCREMENT BY 1;