CREATE TABLE IF NOT EXISTS BOARD
    (ID int(11),
    TITLE VARCHAR(255),
    CONTENTS BLOB,
    IMAGES VARCHAR(255),
    WRITER_ID INTEGER,
    REGIST_DATE DATETIME DEFAULT NOW(),
    UPDATE_DATE DATETIME DEFAULT NOW(),
    DELETE_YN CHAR DEFAULT 'N',
    DELETE_DATE DATETIME,
    PRIMARY KEY (ID));

CREATE SEQUENCE IF NOT EXISTS BOARD_ID_SEQ START WITH 1 INCREMENT BY 1;