CREATE TABLE IF NOT EXISTS BOARD
    (ID int(11) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255),
    CONTENTS BLOB,
    IMAGES VARCHAR(255),
    WRITER_ID INTEGER,
    CREATE_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATE_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP,
    DELETE_YN CHAR DEFAULT 'N',
    DELETE_DATE DATETIME(6),
    PRIMARY KEY (ID));

CREATE SEQUENCE IF NOT EXISTS BOARD_ID_SEQ START WITH 1 INCREMENT BY 1;